Lobby:
  lobby_world_name: world
  disable_damage: true
  infinity_food: true
  spawn:
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
database:
    use_mysql: true
    table: QuartzDefenders
    host: localhost
    port: 3306
    database: database
    username: user
    password: password