name: QuartzDefenders
version: 3.1
api-version: 1.13
main: ua.endertainment.quartzdefenders.QuartzDefenders
database: true
commands:
  quartzdefenders:
    usage: /<command> help
    aliases: [qd, quartz, qdef]
  team:
    usage: /<command> help
  stats:
    usage: /<command> help 
  gamebroadcast:
    usage: /<command> <message>
    aliases: [bc, gbc, gamebc, bcast]
  game:
    usage: /<command> help
  kit:
    usage: /<command> help
